### PR TITLE
Add Thoth.Json

### PR DESCRIPTION
**Pull request by MangelMaxime**

### CODE REVIEW

**Comment by bartelink** [comment]
For multi-case union, https://github.com/jet/Jet.ConfluentKafka.FSharp has an impl and tests that may be worth grabbing

**Comment by MangelMaxime** [comment]
Hello @vsapronov really happy that you like Thoth.Json :)

You can always define a manual decoder/encoder and have 100% control over the JSON representation.

But it's true that if you use "Auto decoder/encoder" then you are a bit more limited. 

In version 3 of Thoth.Json we are adding the possibility to extend and override the behaviour for a given type. [Documentation](https://mangelmaxime.github.io/Thoth/json/v3.html#extra-coders).

For example, auto decoders in Thoth.Json weren't supporting classes (except special cases) but with v3 you can now have classes support.

**Comment by vsapronov** [comment]
As a side conversation: What do you think about Newtonsoft as a core of your library? What are advantages? What are disadvantages? Any plans to use something else inside of Thoth.Json.Net? I have my opinions on these but interested to know other experiences who went through similar path as I did.

By the way, I'm speaking about Json (de)serialization at F# eXchange in L9ndon this week. I would like to mention Thoth.Json for sure. Anything I should pay attention specifically? I know Fable is a killer feature. Anything else?

**Comment by MangelMaxime** [comment]
@vsapronov Cool we will be able to meet their :) I am attending F# Exchange.

> What do you think about Newtonsoft as a core of your library? What are advantages? What are disadvantages?

Well, what I don't like about Newtonsoft, in general, is auto serialization but I don't use it in Thoth.Json.Net as I am working at the JToken level. However, Newtonsoft still tries to interpret the JSON value. So for example, if you pass it a string and it detects the string as valid DateTime format it will give you a DateTime and I find it really annoying.

I am using Thoth.Json only in my project and made Thoth.Json.Net only because people asked support for it so I don't have much experience to share about it.

I am indeed planning in version 4 of Thoth.Json to rewrite the core of the library in order to make it easier to share the code between Fable and .Net/NetCore runtime. At the moment, people need to use compiler directive and it is not really friendly. 

So the idea is to make Thoth.Json(.Core) JSON library agnostic and so people will be able to use `Newtonsoft`, `standard JavaScript API`, their own parser, etc. 

> Any plans to use something else inside of Thoth.Json.Net?

If I am unable able to make coding sharing easy by using a standard contact then I will write my own JSON parser in F#. I saw someone wrote one in less than 100 lines I think so the same code will be executed on the server and client.

I first want to try keeping `Newtonsoft`, `standard JavaScript API` because I believe they should be more performant than a "naive" JSON parser.

> I would like to mention Thoth.Json for sure. Anything I should pay attention to specifically? I know Fable is a killer feature. Anything else?

I don't really know how to choose between what I see as selling points for Thoth.Json so I will do a list and let you decide :)

The most important points for me:

- Strongly opinionated API for the manual decoders based only on functions so it's easy to read even for someone who doesn't know Thoth.Json. (Read it as there is no custom operator)
- Encourage you to handle the error when parsing JSON
    - Human-friendly error, for example, it output the JSONPath where the error. And not error at char 1000...
- You can customize a lot of things and well have 100% control over your JSON
- Type safe JSON, it check that the JSON received is valid. Which most auto-magic JSON library don't.

Secondary?

- Support both manual and auto decoder
    - With the newest version mixing both is becoming easier and easier
- Same API for .Net and Fable side
- The F# compiler helps you write your manual decoders thanks to type inference.

**Comment by bartelink** [comment]
> So for example, if you pass it a string and it detects the string as valid DateTime format it will give you a DateTime and I find it really annoying.

See https://github.com/JamesNK/Newtonsoft.Json/issues/862 - there is an "arguably" ill-chosen default that can be flipped to remove this behaviour

**Comment by MangelMaxime** [comment]
Indeed seems like a odd choices with not much justifications. Thanks you for the link, I will take a deeper look at it later and perhaps choose to disable the auto convert feature.:)

**Pull request merged**
